### ISSUE TITLE
What’s the context of CP here?

### ISSUE THREAD

**Issue by ollypsilon** [indieVelo/translations#14]
https://github.com/indieVelo/translations/blob/416c2daaafdc4c4eca2e0b3b5bb9dce7d36e60f4/de-DE.json#L314

I assume it’s critical power, if so I wouldn’t translate it and keep term CP. Other terms like FTP won’t be translated either.

**Comment by indieVelo** [comment]
Yes, CP in this context means Critical Power, so probably shouldn't be translated unless there's an alternate locale specific phrase that's in common use within that language.

**Comment by Andras-Beck** [comment]
I have left this one as "CP" for Hungarian as we don't have a proper translation for Critical Power. Where Critical Power was displayed to full extent, I have translated it, but left (CP) after it, like "Kritikus Teljesítmény(CP)".
