### ISSUE TITLE
Formal or informal salutation?

### ISSUE THREAD

**Issue by ollypsilon** [indieVelo/translations#27]
https://github.com/indieVelo/translations/blob/5aeea42cf3f0872b8de97f2c671176c1cfcad002/de-DE.json#L286
https://github.com/indieVelo/translations/blob/5aeea42cf3f0872b8de97f2c671176c1cfcad002/de-DE.json#L287

For German translation and maybe other languages which have it: should the formal language ("Sie/Ihre" etc.) be used or the informal language ("Du"/"Dein" etc.)? It's a bit mixed. Just cosmetics by my inner monk doesn't like it 😉

**Comment by indieVelo** [comment]
It should be informal - I'll add a note to the instructions to make that clear for all languages ("tu" rather than "vous" etc).

**Comment by demon2307** [comment]
When you meet a cyclist on the road, do you say hello or good day?

**Comment by ollypsilon** [comment]
> It should be informal - I'll add a note to the instructions to make that clear for all languages ("tu" rather than "vous" etc).

Ok, I'll update German translations accordingly.
